"""Answer validator for AI Curator LLM responses."""

import re
from dataclasses import dataclass
from typing import Any, Dict, List, Optional


@dataclass
class ValidationResult:
    """Result of answer validation."""

    is_valid: bool
    answer: str
    issues: List[str]
    fallback: bool = False


class AnswerValidator:
    """Validate LLM answer against safety and quality rules."""

    FORBIDDEN_PATTERNS = [
        r"оценка\s*[:=]?\s*[0-9]+",
        r"ставлю\s+оценку",
        r"измен[ию]\s+(дедлайн|задание|расписание)",
        r"удал[ию]\s+(задание|курс|модуль)",
    ]

    # Markdown links that look like [text](number) — LLM sometimes generates fake KB links
    FAKE_KB_LINK_PATTERN = re.compile(r"\[([^\]]+)\]\s*\((\d+)\)")

    def __init__(self, answer: str, sources: List[Dict[str, Any]], has_lms_or_rag_context: bool):
        self.answer = answer
        self.sources = sources
        self.has_context = has_lms_or_rag_context
        self.issues: List[str] = []

    def validate(self) -> ValidationResult:
        """Run validation rules and return normalized result."""
        self._check_empty()
        self._check_forbidden_actions()
        self._check_sources()

        if self.issues:
            fallback_answer = self.sanitize_answer()
            # If sanitized answer still has meaningful content and sources, use it instead of generic fallback
            if (
                len(fallback_answer.strip()) > 30
                and not self.FAKE_KB_LINK_PATTERN.search(fallback_answer)
                and self.sources
            ):
                return ValidationResult(
                    is_valid=True,
                    answer=fallback_answer,
                    issues=self.issues,
                    fallback=False,
                )
            return ValidationResult(
                is_valid=False,
                answer=self._build_fallback(),
                issues=self.issues,
                fallback=True,
            )

        return ValidationResult(
            is_valid=True,
            answer=self.answer,
            issues=[],
        )

    def _check_empty(self) -> None:
        if not self.answer or not self.answer.strip():
            self.issues.append("Ответ пустой.")

    def _check_forbidden_actions(self) -> None:
        lower = self.answer.lower()
        for pattern in self.FORBIDDEN_PATTERNS:
            if re.search(pattern, lower):
                self.issues.append(f"Ответ содержит запрещённое действие: {pattern}")

    def _check_sources(self) -> None:
        if self.has_context and not self.sources:
            self.issues.append("Ответ не содержит источников, хотя контекст есть.")
        # Detect self-generated fake KB links like [Фрагмент 1](84)
        if self.FAKE_KB_LINK_PATTERN.search(self.answer):
            self.issues.append("Ответ содержит самодельные markdown-ссылки на KB вместо предоставленных источников.")

    def sanitize_answer(self) -> str:
        """Remove or normalize fake markdown links generated by LLM."""
        # Replace [text](number) with plain text, keeping the label
        sanitized = self.FAKE_KB_LINK_PATTERN.sub(r"\1", self.answer)
        return sanitized

    def _build_fallback(self) -> str:
        return (
            "Я не смог сформировать надёжный ответ на ваш вопрос. "
            "Пожалуйста, переформулируйте запрос или обратитесь к преподавателю."
        )
