"""add knowledge base tables v2

Revision ID: cdf35de86289
Revises: eb3c743f028b
Create Date: 2026-07-29 20:51:55.437820+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf35de86289'
down_revision: Union[str, None] = '55831f11fdf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.Enum('LECTURE', 'METHODICAL', 'FAQ', 'INSTRUCTION', 'GLOSSARY', 'EXAMPLE', 'EXTERNAL', name='document_type'), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficulty_level'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PROCESSING', 'INDEXED', 'ERROR', 'ARCHIVED', name='document_status'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_documents_course_id'), 'kb_documents', ['course_id'], unique=False)
    op.create_index(op.f('ix_kb_documents_id'), 'kb_documents', ['id'], unique=False)
    op.create_index(op.f('ix_kb_documents_module_id'), 'kb_documents', ['module_id'], unique=False)
    op.create_index(op.f('ix_kb_documents_topic_id'), 'kb_documents', ['topic_id'], unique=False)
    op.create_table('kb_document_versions',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PROCESSING', 'INDEXED', 'ERROR', 'ARCHIVED', name='document_status'), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['kb_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_document_versions_document_id'), 'kb_document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_kb_document_versions_id'), 'kb_document_versions', ['id'], unique=False)
    op.create_table('kb_document_chunks',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PROCESSING', 'INDEXED', 'ERROR', 'ARCHIVED', name='document_status'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['kb_document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_document_chunks_id'), 'kb_document_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_kb_document_chunks_version_id'), 'kb_document_chunks', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_document_chunks_version_id'), table_name='kb_document_chunks')
    op.drop_index(op.f('ix_kb_document_chunks_id'), table_name='kb_document_chunks')
    op.drop_table('kb_document_chunks')
    op.drop_index(op.f('ix_kb_document_versions_id'), table_name='kb_document_versions')
    op.drop_index(op.f('ix_kb_document_versions_document_id'), table_name='kb_document_versions')
    op.drop_table('kb_document_versions')
    op.drop_index(op.f('ix_kb_documents_topic_id'), table_name='kb_documents')
    op.drop_index(op.f('ix_kb_documents_module_id'), table_name='kb_documents')
    op.drop_index(op.f('ix_kb_documents_id'), table_name='kb_documents')
    op.drop_index(op.f('ix_kb_documents_course_id'), table_name='kb_documents')
    op.drop_table('kb_documents')
    # ### end Alembic commands ###
