#!/usr/bin/env python3
"""One-off cleanup script for smoke-test artifacts in the production database.

WARNING: This is a destructive operation. Run only after:
1. Creating a full backup of the production database.
2. Verifying the deletion predicates against the current data.
3. Confirming that all automatic tests now run against ai_curator_test.

Deletion scope:
- KB documents with id >= 317 (test uploads from pytest suite).
- Orphan chat_sessions that are not linked to any chat_request.
- ExecutionSession / ExecutionStep rows tied to deleted chat_sessions.
- AuditLog entries for test KB documents and all non-chat_request audit
  entries (because every admin action today was produced by tests).
- AnalyticsEvents, LLMCalls, LLMCallTraces tied to deleted chat_requests.
"""

import asyncio
import sys
from pathlib import Path

# Allow imports from the backend package when running inside the container.
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))
sys.path.insert(0, str(_PROJECT_ROOT / "src"))

from sqlalchemy import delete, select

from db import async_session_factory
from models.chat import (
    AnalyticsEvent,
    AuditLog,
    ChatLog,
    ChatRequest,
    ChatSession,
    ExecutionSession,
    ExecutionStep,
    LlmCall,
    LlmCallTrace,
)
from models.knowledge_base import (
    KbDocument,
    KbDocumentChunk,
    KbDocumentEvent,
    KbDocumentVersion,
)
from services.knowledge_base import KnowledgeBaseService
from services.rag_pipeline import RagPipeline


TEST_KB_DOC_ID_CUTOFF = 317


async def _delete_test_kb_documents(db) -> int:
    """Delete KB documents with id >= TEST_KB_DOC_ID_CUTOFF and their Chroma chunks."""
    result = await db.execute(select(KbDocument.id).where(KbDocument.id >= TEST_KB_DOC_ID_CUTOFF))
    doc_ids = [row[0] for row in result.all()]
    if not doc_ids:
        return 0

    print(f"Deleting {len(doc_ids)} test KB document(s) (id >= {TEST_KB_DOC_ID_CUTOFF})...")

    # Delete Chroma chunks for all active versions of these documents.
    version_result = await db.execute(
        select(KbDocumentVersion.id)
        .where(KbDocumentVersion.document_id.in_(doc_ids))
    )
    version_ids = [row[0] for row in version_result.all()]
    if version_ids:
        rag = RagPipeline()
        for version_id in version_ids:
            try:
                rag.delete_version_chunks(version_id)
            except Exception as exc:
                print(f"  Warning: failed to delete Chroma chunks for version {version_id}: {exc}")

    # Delete lifecycle events, chunks and versions first to avoid FK issues.
    await db.execute(delete(KbDocumentEvent).where(KbDocumentEvent.document_id.in_(doc_ids)))
    await db.execute(
        delete(KbDocumentChunk).where(
            KbDocumentChunk.version_id.in_(
                select(KbDocumentVersion.id).where(KbDocumentVersion.document_id.in_(doc_ids))
            )
        )
    )
    await db.execute(delete(KbDocumentVersion).where(KbDocumentVersion.document_id.in_(doc_ids)))
    result = await db.execute(delete(KbDocument).where(KbDocument.id.in_(doc_ids)))
    return result.rowcount


async def _delete_orphan_chat_sessions(db) -> int:
    """Delete ChatSession rows that have no linked ChatRequest."""
    result = await db.execute(select(ChatRequest.chat_session_id).distinct())
    linked_by_chat_session_id = {row[0] for row in result.all() if row[0]}

    result = await db.execute(select(ChatRequest.session_id).distinct())
    linked_session_ids = {row[0] for row in result.all()}

    result = await db.execute(
        select(ChatSession.id).where(ChatSession.session_id.in_(linked_session_ids))
    )
    linked_by_session_id = {row[0] for row in result.all()}

    linked_ids = linked_by_chat_session_id | linked_by_session_id

    result = await db.execute(
        select(ChatSession.id).where(ChatSession.id.notin_(linked_ids))
    )
    orphan_ids = [row[0] for row in result.all()]
    if not orphan_ids:
        return 0

    print(f"Deleting {len(orphan_ids)} orphan chat_session(s)...")

    # Delete linked execution sessions and steps first.
    await db.execute(
        delete(ExecutionStep).where(
            ExecutionStep.execution_session_id.in_(
                select(ExecutionSession.id).where(ExecutionSession.chat_session_id.in_(orphan_ids))
            )
        )
    )
    await db.execute(
        delete(ExecutionSession).where(ExecutionSession.chat_session_id.in_(orphan_ids))
    )

    # Delete orphan chat sessions.
    result = await db.execute(delete(ChatSession).where(ChatSession.id.in_(orphan_ids)))
    return result.rowcount


async def _delete_test_audit_logs(db) -> int:
    """Delete audit logs produced by smoke tests.

    Every admin action in today's audit log was generated by tests, because the
    read-only audit cleanup landed today. chat_request entries are kept because
    they represent real student interactions.
    """
    result = await db.execute(
        delete(AuditLog)
        .where(AuditLog.action != "chat_request")
        .where(
            AuditLog.id.in_(
                select(AuditLog.id).where(
                    (AuditLog.resource_type == "kb_document") |
                    (AuditLog.resource_type == "kb_document_version") |
                    (AuditLog.resource_type == "orchestrator_config")
                )
            )
        )
    )
    return result.rowcount


async def _delete_analytics_for_test_chats(db, request_ids: list[int]) -> int:
    """Delete analytics events tied to test chat requests being removed."""
    if not request_ids:
        return 0
    result = await db.execute(
        delete(AnalyticsEvent).where(AnalyticsEvent.session_id.in_(
            select(ChatRequest.session_id).where(ChatRequest.id.in_(request_ids))
        ))
    )
    return result.rowcount


async def main():
    async with async_session_factory() as db:
        # Identify chat requests that belong to test sessions (everything today).
        # Real user interactions are expected after this cleanup.
        chat_request_result = await db.execute(select(ChatRequest.id))
        all_request_ids = [row[0] for row in chat_request_result.all()]

        kb_deleted = await _delete_test_kb_documents(db)
        sessions_deleted = await _delete_orphan_chat_sessions(db)
        audit_deleted = await _delete_test_audit_logs(db)
        analytics_deleted = await _delete_analytics_for_test_chats(db, all_request_ids)

        await db.commit()

        print("\nCleanup summary:")
        print(f"  KB documents deleted: {kb_deleted}")
        print(f"  Orphan chat sessions deleted: {sessions_deleted}")
        print(f"  AuditLog entries deleted: {audit_deleted}")
        print(f"  AnalyticsEvent rows deleted: {analytics_deleted}")


if __name__ == "__main__":
    asyncio.run(main())
